CREATE SEQUENCE IF NOT EXISTS pedido_numero_seq START 1;
CREATE SEQUENCE IF NOT EXISTS factura_numero_seq START 1;
CREATE SEQUENCE IF NOT EXISTS embarque_numero_seq START 1;
CREATE SEQUENCE IF NOT EXISTS abono_numero_seq START 1;
CREATE SEQUENCE IF NOT EXISTS compra_numero_seq START 1;
